version: '3.9'

services:

  app:
    container_name: flask_container
    image: flask_app:v1
    build:
      context: .
    ports: 
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_ENV=development
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DATABASE=vehicles_db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
    depends_on:
      - db

  db:
    container_name: postgres_container
    image: "postgres:12"
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vehicles_db
    volumes:
      - /data/postgres:/var/lib/postgresql/data
      - ./src/database/migrations:/docker-entrypoint-initdb.d
volumes:
  postgres_data: {}