version: '3.9'

services:

  app:
    container_name: flask_container
    image: flask_app:v1
    build:
      context: .
    ports: 
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_ENV=production
      - AWS_PG_HOST=my-instance.c1h8v31yc36v.us-east-1.rds.amazonaws.com
      - AWS_PG_PORT=5432
      - AWS_PG_DATABASE=vehicles_db
      - AWS_PG_USER=postgres
      - AWS_PG_PASS=postgres
      - VEHICLES_API=https://datos.cdmx.gob.mx/api/3/action/datastore_search?resource_id=ad360a0e-b42f-482c-af12-1fd72140032e&limit=1000
      - GEOCODER_API=https://maps.googleapis.com/maps/api/geocode/json?
      - GEOCODER_API_KEY=AIzaSyCZgr16JUc3aW1jeuYam3FaWHW89PfY08Q