version: '3.9'

services:

  flask_app:
    container_name: flask_container
    image: flask_app:v1
    build:
      context: .
    ports: 
      - "5000:5000"
    environment:
      - PORT=5000
      - FLASK_ENV=development
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_container
    image: "postgres:12"
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vehicles_db
    volumes:
      - /data:/var/lib/postgresql/data
volumes:
  postgres_data: {}